"""Run sql/validation/validation_suite.sql and publish the results.

Read-only: the suite runs inside a READ ONLY transaction.
Writes docs/validation_results.md and exits with code 1 if any Error-severity check fails.

Usage (from the repository root):
    python python/validation/run_validation_suite.py
"""
import sys
from datetime import datetime
from pathlib import Path

import pandas as pd
from sqlalchemy import text

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "python" / "data_generation"))
from data_generator import engine  # noqa: E402  (shared DB connection from .env)

SUITE = ROOT / "sql" / "validation" / "validation_suite.sql"
REPORT = ROOT / "docs" / "validation_results.md"

AREA_ORDER = [
    "Data quality", "Lifecycle", "Audit trail", "Customer risk",
    "Entity network", "Power BI layer", "Baseline v1.0",
]


def run_suite() -> pd.DataFrame:
    sql = SUITE.read_text(encoding="utf-8")
    with engine.connect() as conn:
        conn.execute(text("SET TRANSACTION READ ONLY"))
        return pd.read_sql(text(sql), conn)


def to_markdown(df: pd.DataFrame, run_at: str) -> str:
    counts = df["result"].value_counts()
    lines = [
        "# Validation Results",
        "",
        f"Generated by `python/validation/run_validation_suite.py` on {run_at} "
        f"from [`validation_suite.sql`](../sql/validation/validation_suite.sql).",
        "",
        f"**{len(df)} checks: {counts.get('PASS', 0)} PASS, "
        f"{counts.get('WARN', 0)} WARN, {counts.get('FAIL', 0)} FAIL**",
        "",
        "| Area | Checks | PASS | WARN | FAIL |",
        "|---|---:|---:|---:|---:|",
    ]
    for area in AREA_ORDER:
        part = df[df["area"] == area]
        if part.empty:
            continue
        c = part["result"].value_counts()
        lines.append(f"| {area} | {len(part)} | {c.get('PASS', 0)} | {c.get('WARN', 0)} | {c.get('FAIL', 0)} |")

    lines += [
        "",
        "## Check detail",
        "",
        "| ID | Type | Check | Expected | Actual | Result |",
        "|---|---|---|---|---|---|",
    ]
    for r in df.itertuples():
        lines.append(
            f"| {r.check_id} | {r.check_type} | {r.check_name} | {r.expected} | {r.actual} | **{r.result}** |"
        )

    warns = df[df["result"] == "WARN"]
    if not warns.empty:
        lines += ["", "## Warnings (documented limitations)", ""]
        for r in warns.itertuples():
            lines.append(f"- **{r.check_id}**: {r.check_name}. Actual: {r.actual}.")
    return "\n".join(lines) + "\n"


def main() -> int:
    run_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    df = run_suite()

    with pd.option_context("display.max_rows", None, "display.max_colwidth", 70, "display.width", 200):
        print(df[["check_id", "check_name", "expected", "actual", "result"]].to_string(index=False))

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(to_markdown(df, run_at), encoding="utf-8")

    counts = df["result"].value_counts()
    print(f"\n{len(df)} checks: {counts.get('PASS', 0)} PASS, "
          f"{counts.get('WARN', 0)} WARN, {counts.get('FAIL', 0)} FAIL")
    print(f"Report written to {REPORT.relative_to(ROOT)}")
    return 1 if counts.get("FAIL", 0) else 0


if __name__ == "__main__":
    sys.exit(main())
